spring:
  application:
    name: persona-chats
  datasource:
    url: jdbc:postgresql://localhost:5432/persona_db
    username: persona_user
    password: secret1234
  jpa:
    hibernate:
      ddl-auto: validate
  ai:
    model:
      chat: bedrock-converse
    bedrock:
      aws:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
        region: ${AWS_REGION}
      converse:
        chat:
          enabled: true
          model: ${AWS_MODEL}
  cloud:
    consul:
      discovery:
        prefer-ip-address: true
server:
  port: 8002
management:
  endpoints:
    web:
      exposure:
        include: health